### ISSUE TITLE
Image naming convention

### ISSUE THREAD

**Issue by branrickman** [clear-code-projects/UltimatePygameIntro#2]
Sky.png and ground.png are the names used in the graphics folder. The difference in capitalization convention may throw off new programmers.

(Fantastic video by the way- this is the gold standard I'll be measuring other coding tutorials against from now on)

**Comment by branrickman** [comment]
Ah, you addressed it later in the video. Disregard this issue.

**Comment by rafrafek** [comment]
Capitalization is not only convention. On Linux systems it is required to match capitalization in files and code.
